services:
  homeassistant:
    container_name: choreminder-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./dev/config:/config
      - ./custom_components/choreminder:/config/custom_components/choreminder:ro
      - ./custom_components/choreminder/www:/config/www/choreminder:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=America/Los_Angeles
    restart: "no"
